version: "3.8"
services:
  web:
    build: ./web
    environment:
      - MARIADB_HOST=${HOST}
      - MARIADB_USER=${USER}
      - MARIADB_PASSWORD=${PASSWORD}
    ports:
      - "5000:5000"
    restart: on-failure
    env_file:
      - ./web/.env