version: "3.8"
services:
  db:
    build: ./db
    volumes:
      - "./.mdbdata/mdb10:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - ./db/.env
  web:
    build: ./web
    environment:
      - MARIADB_HOST=${HOST}
      - MARIADB_USER=${USER}
      - MARIADB_PASSWORD=${PASSWORD}
      - MARIADB_DATABASE=${DATABASE}
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure
    env_file:
      - ./web/.env
